'id' INTEGER PRIMARY KEY AUTOINCREMENT,
      'first_name' VARCHAR(255) NOT NULL,
      'last_name' VARCHAR(255),
      'email' VARCHAR(255) NOT NULL,
      'phone' VARCHAR(50) NOT NULL,
      'country' INT,
      'state' INT,
      'city' VARCHAR(255),
      'zip_code' INT,
      'attendance_time' INT,
      'employee_type' INT,

      'account_number' INT NOT NULL,
      'bank_name' VARCHAR(255) NOT NULL,
      'bban_number' VARCHAR(255) NOT NULL,
      'branch_name' VARCHAR(255) NOT NULL,

      'division' INT NOT NULL,
      'hire_date' INT,
      'pay_frequency_text' VARCHAR(255) NOT NULL,
      'home_department' VARCHAR(255) NOT NULL,
      'termination_date' INT,
      'termination_reason' TEXT NOT NULL,
      'designation' INT NOT NULL,
      'original_hire_date' INT,
      'voluntary_termination' INT NOT NULL,
      'pay_frequency' INT NOT NULL,
      'hourly_rate2' REAL NOT NULL,
      'department_text' VARCHAR(255) NOT NULL,
      'duty_type' INT NOT NULL,
      're_hire_date' INT,
      'rate_type' INT NOT NULL,
      'rate' REAL NOT NULL,
      'hourly_rate3' INT NOT NULL,

      'benefit_class_code' VARCHAR(255),
      'benefit_accrual_date' INT,
      'benefit_description' TEXT,
      'benefit_status' INT,

      'supervisor_name' INT,
      'supervisor_report' VARCHAR(255),
      'is_supervisor' INT,

      'date_of_birth' INT NOT NULL,
      'eeo_class' VARCHAR(255),
      'work_in_state' VARCHAR(255),
      'gender' VARCHAR(50) NOT NULL,
      'ethnic_group' VARCHAR(255),
      'live_in_state' VARCHAR(255),
      'marital_status' VARCHAR(100),
      'ssn' VARCHAR(255),
      'citizenship' VARCHAR(255),

      'home_email' VARCHAR(255),
      'home_phone' VARCHAR(50),
      'cell_phone' VARCHAR(50),
      'business_email' VARCHAR(255),
      'business_phone' VARCHAR(50),

      'emergency_contact' VARCHAR(50),
      'emergency_work_phone' VARCHAR(50),
      'alter_emergency_contact' VARCHAR(50),
      'alt_emergency_work_phone' VARCHAR(50),
      'emergency_home_phone' VARCHAR(50),
      'emergency_contact_relation' VARCHAR(50),
      'alt_emergency_home_phone' VARCHAR(50),

      'custom_field_name' VARCHAR(255),
      'custom_value' VARCHAR(255),
      'custom_field_type' VARCHAR(255)
      )

INSERT INTO employees (
first_name,
last_name,
email,
phone,
country,
state,
city,
zip_code,
attendance_time,
employee_type,
account_number,
bank_name,
bban_number,
branch_name,
division,
hire_date,
pay_frequency_text,
home_department,
termination_date,
termination_reason,
designation,
original_hire_date,
voluntary_termination,
pay_frequency,
hourly_rate2,
department_text,
duty_type,
re_hire_date,
rate_type,
rate,
hourly_rate3
benefit_class_code,
benefit_accrual_date,
benefit_description,
benefit_status,
supervisor_name,
supervisor_report,
is_supervisor,
date_of_birth,
eeo_class,
work_in_state,
gender,
ethnic_group,
live_in_state,
marital_status,
ssn,
citizenship,
home_email,
home_phone,
cell_phone,
business_email,
business_phone,
emergency_contact,
emergency_work_phone,
alter_emergency_contact,
alt_emergency_work_phone,
emergency_home_phone,
emergency_contact_relation,
alt_emergency_home_phone,
custom_field_name,
custom_value,
custom_field_type
)


basic_salary,
house_rent,
medical,
others_allowance,
gross_salary,
tranport_allowance
